[project]
name = "Quick Test Config"
output_dir = "output"

[[iterations]]
name = "quick"

[iterations.datagen]
enabled = true
relations = [
  { name = "rel0", num_rows = 100, attributes = [
    { name = "attr0" },
    { name = "attr1" },
    { name = "attr2" },
  ] },
  { name = "rel1", num_rows = 100, attributes = [
    { name = "attr0" },
    { name = "attr1" },
    { name = "attr2" },
  ] },
  { name = "rel2", num_rows = 100, attributes = [
    { name = "attr0" },
    { name = "attr1" },
    { name = "attr2" },
  ] },
  { name = "rel3", num_rows = 100, attributes = [
    { name = "attr0" },
    { name = "attr1" },
    { name = "attr2" },
  ] },
]

[iterations.plangen]
visualize = true
base_plans = [{ pattern = "random" }]

[iterations.analysis]
enabled = true
